In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [50]:
fs_9_df = pd.read_csv('../data/fs_sept.csv')

In [3]:
fs_df = pd.read_csv('../data/fullsample.csv')
fs_df['BEGIN'] = pd.to_datetime(fs_df['BEGIN'], format='%Y-%m-%dT%H:%M:%S', errors='coerce')
fs_df['END'] = pd.to_datetime(fs_df['END'], format='%Y-%m-%dT%H:%M:%S', errors='coerce')
fs_9_df = fs_df[(fs_df['BEGIN'].dt.month == 9)]

In [4]:
fs_9_df['USEDMEM'] = pd.to_numeric(fs_9_df['USEDMEM'].str[:-1], errors='coerce')

C:\Users\georg\anaconda3\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [5]:
count = 0

In [6]:
print(count)
display(fs_9_df.sort_values('USEDMEM', ascending=False)[count:count+10])
count += 10

0

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE
840540,32809841,COMPLETED,2021-09-26 20:34:07,2021-09-27 01:23:27,1024000Mn,874212.35,06:00:00,04:49:20,1,1,cgw-platypus,0:0
838530,32806080,COMPLETED,2021-09-26 13:34:19,2021-09-26 13:46:03,819200Mn,756715.80,2-00:00:00,00:11:44,1,3,cgw-platypus,0:0
839586,32807672_2,COMPLETED,2021-09-26 18:28:53,2021-09-26 18:55:42,716800Mn,705842.12,06:00:00,00:26:49,1,35,production,0:0
839585,32807672_1,COMPLETED,2021-09-26 16:08:26,2021-09-26 20:05:11,716800Mn,677430.88,06:00:00,03:56:45,1,35,production,0:0
47327,31947977,COMPLETED,2021-09-01 19:20:11,2021-09-01 19:55:04,614400Mn,594770.75,6-08:00:00,00:34:53,1,32,production,0:0
47458,31948876,COMPLETED,2021-09-01 20:09:08,2021-09-02 05:41:50,614400Mn,591345.64,6-08:00:00,09:32:42,1,32,production,0:0
839588,32807672_4,COMPLETED,2021-09-26 20:05:21,2021-09-26 23:45:03,716800Mn,557137.07,06:00:00,03:39:42,1,35,production,0:0
36722,31940995,COMPLETED,2021-09-01 16:03:31,2021-09-01 16:09:10,512000Mn,536055.45,6-08:00:00,00:05:39,1,32,production,0:0
836737,32802769,COMPLETED,2021-09-26 01:00:27,2021-09-26 07:18:20,524288Mn,509928.39,2-00:00:00,06:17:53,1,2,cgw-platypus,0:0
839587,32807672_3,COMPLETED,2021-09-26 18:59:38,2021-09-26 22:26:53,716800Mn,489745.48,06:00:00,03:27:15,1,35,production,0:0

In [8]:
ce5_df = pd.read_csv('../data/ce5_9024_sbatch.csv')
ce6_df = pd.read_csv('../data/ce6_9024_sbatch.csv')
ce5_df['0'] = pd.to_datetime(ce5_df['0'], format='%Y-%m-%dT%H:%M:%S')
ce6_df['0'] = pd.to_datetime(ce6_df['0'], format='%Y-%m-%dT%H:%M:%S')
ce5_9_df = ce5_df[(ce5_df['0'].dt.month == 9)]
ce6_9_df = ce6_df[(ce6_df['0'].dt.month == 9)]
ce5_9_df['4'] = ce5_9_df['4'].str.extract(r'(\d)')
ce6_9_df['4'] = ce6_9_df['4'].str.extract(r'(\d)')

C:\Users\georg\anaconda3\lib\site-packages\pandas\core\frame.py:3599: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item_frame_value(key, value)

In [9]:
list(ce5_9_df[ce5_9_df['4'] == '1']['0'])

[Timestamp('2021-09-01 16:59:56.982884'),
 Timestamp('2021-09-02 21:10:40.539802'),
 Timestamp('2021-09-07 14:42:05.713409'),
 Timestamp('2021-09-07 15:32:21.173736'),
 Timestamp('2021-09-07 16:00:01.852442'),
 Timestamp('2021-09-07 21:15:10.667075'),
 Timestamp('2021-09-08 00:30:16.487416'),
 Timestamp('2021-09-08 06:40:41.425307'),
 Timestamp('2021-09-08 12:40:54.202140'),
 Timestamp('2021-09-08 12:43:59.970247'),
 Timestamp('2021-09-08 15:55:33.856275'),
 Timestamp('2021-09-09 00:14:14.440021'),
 Timestamp('2021-09-09 07:44:04.307273'),
 Timestamp('2021-09-09 09:40:20.536402'),
 Timestamp('2021-09-09 10:40:22.159830'),
 Timestamp('2021-09-09 12:59:18.630672'),
 Timestamp('2021-09-09 14:25:36.617331'),
 Timestamp('2021-09-09 14:55:59.756787'),
 Timestamp('2021-09-09 16:55:45.527065'),
 Timestamp('2021-09-09 20:59:31.033497'),
 Timestamp('2021-09-10 00:55:23.496132'),
 Timestamp('2021-09-10 02:45:56.106026'),
 Timestamp('2021-09-10 03:25:34.347069'),
 Timestamp('2021-09-10 03:59:41.839418'),
 Timestamp('2021-09-10 05:10:33.368949'),
 Timestamp('2021-09-10 05:29:14.217078'),
 Timestamp('2021-09-10 06:40:32.179112'),
 Timestamp('2021-09-10 07:10:35.058632'),
 Timestamp('2021-09-10 07:29:07.429742'),
 Timestamp('2021-09-10 07:40:26.215791'),
 Timestamp('2021-09-10 10:29:13.999272'),
 Timestamp('2021-09-10 10:40:26.802175'),
 Timestamp('2021-09-12 02:55:35.758007'),
 Timestamp('2021-09-12 04:14:30.142464'),
 Timestamp('2021-09-13 08:25:35.863943'),
 Timestamp('2021-09-14 14:40:44.242882'),
 Timestamp('2021-09-14 18:44:28.596112'),
 Timestamp('2021-09-14 19:14:34.600228'),
 Timestamp('2021-09-14 20:41:08.729124'),
 Timestamp('2021-09-14 21:11:06.494463'),
 Timestamp('2021-09-14 22:55:50.344282'),
 Timestamp('2021-09-18 20:11:06.757809'),
 Timestamp('2021-09-18 23:29:46.941836'),
 Timestamp('2021-09-19 01:41:43.601517'),
 Timestamp('2021-09-19 07:29:37.718522'),
 Timestamp('2021-09-19 10:29:36.324842'),
 Timestamp('2021-09-20 13:29:41.366814'),
 Timestamp('2021-09-21 17:41:27.823848'),
 Timestamp('2021-09-21 22:41:25.560742'),
 Timestamp('2021-09-22 03:59:42.079501'),
 Timestamp('2021-09-22 17:11:28.909204'),
 Timestamp('2021-09-22 18:11:39.191476'),
 Timestamp('2021-09-23 22:41:27.324201'),
 Timestamp('2021-09-23 22:59:34.921328'),
 Timestamp('2021-09-23 23:29:34.811749'),
 Timestamp('2021-09-23 23:41:37.837563'),
 Timestamp('2021-09-24 00:12:09.670207'),
 Timestamp('2021-09-24 00:29:31.250892'),
 Timestamp('2021-09-24 02:14:36.967698'),
 Timestamp('2021-09-24 03:11:42.025171'),
 Timestamp('2021-09-24 03:44:29.539819'),
 Timestamp('2021-09-24 04:13:39.700409'),
 Timestamp('2021-09-24 04:14:33.278790'),
 Timestamp('2021-09-24 04:41:20.110854'),
 Timestamp('2021-09-24 05:11:53.027568'),
 Timestamp('2021-09-24 05:14:37.866252'),
 Timestamp('2021-09-24 06:11:43.133167'),
 Timestamp('2021-09-24 06:44:43.486631'),
 Timestamp('2021-09-24 07:14:36.233034'),
 Timestamp('2021-09-24 08:44:48.205317'),
 Timestamp('2021-09-24 09:41:58.621394'),
 Timestamp('2021-09-24 12:11:34.940124'),
 Timestamp('2021-09-24 13:13:11.616619'),
 Timestamp('2021-09-24 18:14:35.862916'),
 Timestamp('2021-09-24 19:13:14.894282')]

In [10]:
list(ce6_9_df[ce6_9_df['4'] == '1']['0'])

[Timestamp('2021-09-02 21:10:37.366955'),
 Timestamp('2021-09-02 23:06:57.507887'),
 Timestamp('2021-09-03 00:40:46.870840'),
 Timestamp('2021-09-07 19:01:30.357757'),
 Timestamp('2021-09-07 20:00:21.019020'),
 Timestamp('2021-09-07 21:15:17.447709'),
 Timestamp('2021-09-08 04:40:48.476693'),
 Timestamp('2021-09-08 06:56:06.125975'),
 Timestamp('2021-09-08 15:56:17.016024'),
 Timestamp('2021-09-08 16:29:45.389875'),
 Timestamp('2021-09-08 20:41:06.206323'),
 Timestamp('2021-09-08 21:11:02.287984'),
 Timestamp('2021-09-09 11:14:28.280603'),
 Timestamp('2021-09-09 13:14:41.809697'),
 Timestamp('2021-09-09 14:25:53.034869'),
 Timestamp('2021-09-09 14:56:00.569432'),
 Timestamp('2021-09-09 16:55:44.306045'),
 Timestamp('2021-09-09 20:10:52.293795'),
 Timestamp('2021-09-09 23:40:51.464042'),
 Timestamp('2021-09-10 00:10:46.520746'),
 Timestamp('2021-09-10 00:40:55.752245'),
 Timestamp('2021-09-10 02:59:28.740805'),
 Timestamp('2021-09-10 03:59:36.815700'),
 Timestamp('2021-09-10 05:29:37.585703'),
 Timestamp('2021-09-10 06:29:48.439767'),
 Timestamp('2021-09-10 06:40:48.747742'),
 Timestamp('2021-09-10 07:10:57.244878'),
 Timestamp('2021-09-10 07:40:46.230879'),
 Timestamp('2021-09-10 10:29:25.315399'),
 Timestamp('2021-09-12 04:14:28.783930'),
 Timestamp('2021-09-13 10:17:14.961776'),
 Timestamp('2021-09-14 20:14:51.470935'),
 Timestamp('2021-09-18 22:56:37.691402'),
 Timestamp('2021-09-19 09:56:36.972374'),
 Timestamp('2021-09-19 12:14:40.995826'),
 Timestamp('2021-09-21 11:14:42.477567'),
 Timestamp('2021-09-21 15:14:47.835744'),
 Timestamp('2021-09-21 18:14:45.679625'),
 Timestamp('2021-09-21 18:26:47.095141'),
 Timestamp('2021-09-21 21:14:43.680132'),
 Timestamp('2021-09-22 02:26:44.847076'),
 Timestamp('2021-09-22 17:26:37.437089'),
 Timestamp('2021-09-23 23:26:32.991057'),
 Timestamp('2021-09-24 00:15:00.293798'),
 Timestamp('2021-09-24 00:26:37.362121'),
 Timestamp('2021-09-24 00:44:49.319772'),
 Timestamp('2021-09-24 02:11:41.503828'),
 Timestamp('2021-09-24 02:43:03.330924'),
 Timestamp('2021-09-24 02:59:45.594732'),
 Timestamp('2021-09-24 03:41:56.563940'),
 Timestamp('2021-09-24 03:59:52.349070'),
 Timestamp('2021-09-24 04:29:44.757540'),
 Timestamp('2021-09-24 04:41:43.429051'),
 Timestamp('2021-09-24 04:59:55.380742'),
 Timestamp('2021-09-24 05:11:41.508319'),
 Timestamp('2021-09-24 05:59:48.814767'),
 Timestamp('2021-09-24 10:26:43.208762'),
 Timestamp('2021-09-24 13:29:48.498748')]

In [11]:
fs_9_df[(fs_9_df['BEGIN'] > '2021-09-20') & (fs_9_df['BEGIN'] < '2021-09-25')].nlargest(10, 'USEDMEM')

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE
818472,32766201,COMPLETED,2021-09-23 17:32:03,2021-09-24 15:16:04,307200Mn,219529.52,7-00:00:00,21:44:01,1,20,production,0:0
831739,32785359,COMPLETED,2021-09-24 21:42:53,2021-09-25 08:56:09,184320Mn,180690.28,2-00:00:00,11:13:16,1,12,turing,0:0
767248,32672336,COMPLETED,2021-09-20 17:51:06,2021-09-23 17:51:13,251904Mn,175450.71,3-00:00:00,3-00:00:07,1,16,production,0:0
811401,32755640,COMPLETED,2021-09-22 19:55:23,2021-09-22 20:08:19,1013760Mn,152259.35,2-00:00:00,00:12:56,1,36,cgw-hanuman,0:0
813143,32757556,COMPLETED,2021-09-23 07:48:31,2021-09-25 05:26:16,186648Mn,140599.50,2-00:00:00,1-21:37:45,1,32,nogpfs,0:0
764907,32658208_895,COMPLETED,2021-09-22 05:19:04,2021-09-22 05:38:16,256000Mn,131942.83,3-00:00:00,00:19:12,1,13,production,0:0
815427,32762240_406,COMPLETED,2021-09-23 19:26:33,2021-09-23 20:17:15,256000Mn,131852.98,3-00:00:00,00:50:42,1,13,production,0:0
764409,32658208_397,COMPLETED,2021-09-21 02:33:10,2021-09-21 04:01:21,256000Mn,131823.71,3-00:00:00,01:28:11,1,13,production,0:0
764959,32658208_947,COMPLETED,2021-09-22 07:17:22,2021-09-22 07:34:03,256000Mn,131636.34,3-00:00:00,00:16:41,1,13,production,0:0
765185,32658208_1173,COMPLETED,2021-09-22 15:26:51,2021-09-22 15:48:33,256000Mn,131547.45,3-00:00:00,00:21:42,1,13,production,0:0

In [12]:
fs_9_df.nlargest(10, 'USEDMEM')

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE
840540,32809841,COMPLETED,2021-09-26 20:34:07,2021-09-27 01:23:27,1024000Mn,874212.35,06:00:00,04:49:20,1,1,cgw-platypus,0:0
838530,32806080,COMPLETED,2021-09-26 13:34:19,2021-09-26 13:46:03,819200Mn,756715.80,2-00:00:00,00:11:44,1,3,cgw-platypus,0:0
839586,32807672_2,COMPLETED,2021-09-26 18:28:53,2021-09-26 18:55:42,716800Mn,705842.12,06:00:00,00:26:49,1,35,production,0:0
839585,32807672_1,COMPLETED,2021-09-26 16:08:26,2021-09-26 20:05:11,716800Mn,677430.88,06:00:00,03:56:45,1,35,production,0:0
47327,31947977,COMPLETED,2021-09-01 19:20:11,2021-09-01 19:55:04,614400Mn,594770.75,6-08:00:00,00:34:53,1,32,production,0:0
47458,31948876,COMPLETED,2021-09-01 20:09:08,2021-09-02 05:41:50,614400Mn,591345.64,6-08:00:00,09:32:42,1,32,production,0:0
839588,32807672_4,COMPLETED,2021-09-26 20:05:21,2021-09-26 23:45:03,716800Mn,557137.07,06:00:00,03:39:42,1,35,production,0:0
36722,31940995,COMPLETED,2021-09-01 16:03:31,2021-09-01 16:09:10,512000Mn,536055.45,6-08:00:00,00:05:39,1,32,production,0:0
836737,32802769,COMPLETED,2021-09-26 01:00:27,2021-09-26 07:18:20,524288Mn,509928.39,2-00:00:00,06:17:53,1,2,cgw-platypus,0:0
839587,32807672_3,COMPLETED,2021-09-26 18:59:38,2021-09-26 22:26:53,716800Mn,489745.48,06:00:00,03:27:15,1,35,production,0:0