In [69]:
import pandas as pd
import matplotlib.pyplot as plt

In [70]:
with open('../data/slurm_wrapper_ce5.log') as f:
    data5 = ([line.split() for line in f])

In [71]:
ce5 = pd.DataFrame([[x[0] + 'T' + x[1], x[4], float(x[10]), int(x[13]), ''.join(x[16:])] 
                       for x in data5], columns=['BEGIN', 'USER', 'DURATION', 'RC', 'COMMAND'])
# ce5 = pd.DataFrame([[x[0] + 'T' + x[1], x[4], float(x[10]), int(x[13]), x[16]] 
#                        for x in data5], columns=['BEGIN', 'USER', 'DURATION', 'RC', 'COMMAND'])
# ce5['BEGIN'] = pd.to_datetime(ce5['BEGIN'])

In [72]:
ce5['value_grp'] = (ce5.RC.diff(1) != 0).cumsum()

In [73]:
ce5 = ce5.reset_index()

In [74]:
f_index = pd.DataFrame({'Consecutive' : ce5.groupby('value_grp').size(),
                    'index' : ce5.groupby('value_grp').index.first(),
                    'Returncode' : ce5.groupby('value_grp').RC.first()})

In [75]:
fe_index = f_index[f_index['Returncode'] == 1]

In [76]:
fe_df = ce5.join(fe_index['index'].to_frame().set_index('index'), how='inner').sort_values('BEGIN', ascending=False)

In [77]:
fe_df[fe_df['COMMAND'].str.contains('squeue')].sort_values('BEGIN')

,index,BEGIN,USER,DURATION,RC,COMMAND,value_grp
4334941,4334941,2021-08-23T14:08:23.245900,9201,0.090732,1,"['/usr/bin/squeue','-o','%i%T','-j','31584179']",255032
4334943,4334943,2021-08-23T14:08:23.432544,9201,0.186169,1,"['/usr/bin/squeue','-o','%i%T','-j','31584179']",255034
4334956,4334956,2021-08-23T14:10:08.622986,9201,0.639031,1,"['/usr/bin/squeue','-o','%i%T','-j','31505835']",255036
4334978,4334978,2021-08-23T14:11:55.339864,9201,0.811357,1,"['/usr/bin/squeue','-o','%i%T','-j','31584206']",255038
4335022,4335022,2021-08-23T14:19:09.308048,9202,40.145108,1,"['/usr/bin/squeue','-o','%i%T','-u','cmslocal']",255040
...,...,...,...,...,...,...,...
4761564,4761564,2021-10-06T15:39:19.531371,9221,38.057816,1,"['/usr/bin/squeue','-o','%i%T','-j','32915991']",271222
4761568,4761568,2021-10-06T15:39:19.714047,9221,38.042240,1,"['/usr/bin/squeue','-o','%i%T','-j','32915989']",271224
4761570,4761570,2021-10-06T15:39:19.820597,9221,38.050528,1,"['/usr/bin/squeue','-o','%i%T','-j','32916042']",271226
4761575,4761575,2021-10-06T15:39:19.936025,9221,38.052309,1,"['/usr/bin/squeue','-o','%i%T','-j','32916010']",271228
4761585,4761585,2021-10-06T15:39:21.276267,9221,38.036624,1,"['/usr/bin/squeue','-o','%i%T','-j','32916005']",271230

In [78]:
fe_df[fe_df['COMMAND'].str.contains('show')].sort_values('BEGIN')

,index,BEGIN,USER,DURATION,RC,COMMAND,value_grp
357,357,2020-10-16T08:39:50.885933,9201,0.033915,1,"['/usr/bin/scontrol','show','job','24960943']",2
450,450,2020-10-16T08:50:40.257763,9201,0.029021,1,"['/usr/bin/scontrol','show','job','24960817']",4
495,495,2020-10-16T08:54:19.220501,9203,0.219221,1,"['/usr/bin/scontrol','show','job','24995210']",6
506,506,2020-10-16T08:55:14.136565,9201,0.153763,1,"['/usr/bin/scontrol','show','job','24994457']",8
515,515,2020-10-16T08:55:47.640152,9201,0.042904,1,"['/usr/bin/scontrol','show','job','24994471']",10
...,...,...,...,...,...,...,...
4334559,4334559,2021-08-23T13:33:54.898650,9201,0.242896,1,"['/usr/bin/scontrol','show','job','31507124']",255022
4334629,4334629,2021-08-23T13:43:06.458092,9201,0.024283,1,"['/usr/bin/scontrol','show','job','31497016']",255024
4334636,4334636,2021-08-23T13:44:25.770253,9201,0.488467,1,"['/usr/bin/scontrol','show','job','31499824']",255026
4334683,4334683,2021-08-23T13:51:17.168313,9201,0.229178,1,"['/usr/bin/scontrol','show','job','31500336']",255028
4334719,4334719,2021-08-23T13:55:20.088988,9201,0.235950,1,"['/usr/bin/scontrol','show','job','31498441']",255030

In [79]:
7506  + 113507  - 133349

-12336

In [80]:
fe_df[~(fe_df['COMMAND'].str.contains('show')) 
      & ~(fe_df['COMMAND'].str.contains('squeue'))
      & (fe_df['COMMAND'].str.contains('sbatch'))
     ]

,index,BEGIN,USER,DURATION,RC,COMMAND,value_grp
4731181,4731181,2021-10-02T18:29:08.267199,9204,20.043146,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",271132
4730667,4730667,2021-10-02T17:28:16.726151,9201,20.026319,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",271110
4661728,4661728,2021-09-24T20:16:31.458641,9221,20.044075,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",270871
4661384,4661384,2021-09-24T19:13:14.894282,9204,20.051321,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",270859
4661151,4661151,2021-09-24T18:36:59.090081,9201,20.052670,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",270851
...,...,...,...,...,...,...,...
16545,16545,2020-10-16T22:26:14.997088,9201,20.036213,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",533
16405,16405,2020-10-16T22:21:33.319986,9201,20.020155,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",528
16392,16392,2020-10-16T22:21:13.299328,9201,20.030774,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",526
3481,3481,2020-10-16T11:43:54.936191,9202,20.070352,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",106
3465,3465,2020-10-16T11:43:45.753267,9201,20.150959,1,"['/usr/bin/sbatch','/tmp/condor_g_scratch.0x55...",104

In [81]:
fe_df['BEGIN'].dt.hour.value_counts().sort_index()

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
ce5[ce5['COMMAND'].str.contains('show')]

In [ ]:
ce5[(ce5['COMMAND'].str.contains('show')) & (ce5['RC'] == 1)]

In [ ]:
2813268 - 529968

In [ ]:
ce5[(ce5['COMMAND'].str.contains('show')) & (ce5['RC'] == 1) & (ce5['COMMAND'].str.contains('\d'))].shape

In [ ]:
ce5[(ce5['COMMAND'].str.contains('show')) & (ce5['RC'] == 0) & ~(ce5['COMMAND'].str.contains('\d'))].shape

In [ ]:
ce5[(ce5['COMMAND'].str.contains('show')) & (ce5['RC'] == 1) & ~(ce5['COMMAND'].str.contains('\d'))].shape

In [ ]:
command = set(ce5['COMMAND'])

In [ ]:
for x in command:
    print(x)
    print(ce5[(ce5['COMMAND'] == x) & (ce5['RC'] == 1)].shape[0] / ce5[(ce5['COMMAND'] == x) & (ce5['RC'] == 0)].shape[0])

In [82]:
ce5[(ce5['COMMAND'].str.contains('show')) 
    & (ce5['DURATION'] < 15) 
    & (ce5['RC'] == 1) 
    & (ce5['COMMAND'].str.contains('\d'))].shape

(177784, 7)